version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: checklist-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
  api:
    depends_on:
      - mongodb
    container_name: checklist-api
    env_file: .env
    build: ./
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=mongodb
  webapp:
    container_name: checklist-webapp
    image: webapp-dev
    build:
      context: ./webapp
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
volumes:
  mongodb_data:
